openapi: "3.0.0"
info:
  description: >
    # Building Data Models
    
    This repository is going to be archived (Jan-2020) and subsequent works will be carried out
    in [Smart data models] (https://github.com/smart-data-models) repositories. Further questions 
    on migration. alberto.abella@fiware.org
    
    This folders contains a number of data models related to the modelling of
    Building and its management based on
    [GSMA](https://www.gsma.com/iot/iot-big-data/) activities. Compared to GSMA
    models, we introduced some changes and removed the `BuildingType` model.
    
    The following entity types are supported:
    
    -   `Building`: A Building is a human build structure where different activities
        occur related to living, working, healing and so on.
    -   `BuildingOperation`: It captures automated operations that may be ongoing
        within a building.
        
        
  x-description-es: >
    
    # Construyendo modelos de datos
    
    Este repositorio se archivará (enero de 2020) y los trabajos posteriores se llevarán a cabo
    en los repositorios [Modelos de datos inteligentes] (https://github.com/smart-data-models).
    Más preguntas sobre migración. alberto.abella@fiware.org
    
    Esta carpeta contiene varios modelos de datos relacionados con el modelado de
    Edificio y su gestión basada en
    [GSMA] (https://www.gsma.com/iot/iot-big-data/) actividades. En comparación con GSMA
    modelos, introdujimos algunos cambios y eliminamos el modelo `BuildingType`.
    
  version: "1.0.0"
  title: "Building"

tags:
- name: "smart cities"
  description: "Everything about your Smart cities"


paths:
  /nsgi-ld:
    get:
      responses:
        200:
          description: "Linked-data"
          content:
            application/ld+json:
              examples: 
                foo:
                  summary: A foo example
                  value: 

                    id: 'urn:ngsi-ld:Building:building-a85e3da145c1'
                    type: Building
                    modifiedAt: '2016-08-08T10:18:16Z'
                    createdAt: '2016-08-08T10:18:16Z'
                    category:
                      type: Property
                      value:
                        - office
                    floorsBelowGround:
                      type: Property
                      value: 0
                    description:
                      type: Property
                      value: Office block
                    floorsAboveGround:
                      type: Property
                      value: 7
                    occupier:
                      type: Relationship
                      object:
                        - 'urn:ngsi-ld:Person:9830f692-7677-11e6-838b-4f9fb3dc5a4f'
                    mapUrl:
                      type: Property
                      value: 'http://www.example.com'
                    source:
                      type: Property
                      value: 'http://www.example.com'
                    location:
                      type: GeoProperty
                      value:
                        type: Polygon
                        coordinates:
                          - - - 100
                              - 0
                            - - 101
                              - 0
                            - - 101
                              - 1
                            - - 100
                              - 1
                            - - 100
                              - 0
                    address:
                      type: Property
                      value:
                        addressLocality: London
                        postalCode: EC4N 8AF
                        streetAddress: 25 Walbrook
                        type: PostalAddress
                    owner:
                      type: Relationship
                      object:
                        - 'urn:ngsi-ld:Person:cdfd9cb8-ae2b-47cb-a43a-b9767ffd5c84'
                        - 'urn:ngsi-ld:Person:1be9cd61-ef59-421f-a326-4b6c84411ad4'
                    openingHours:
                      type: Property
                      value:
                        - 'Mo-Fr 10:00-19:00'
                        - 'Sa 10:00-22:00'
                        - 'Su 10:00-21:00'
                    dataProvider:
                      type: Property
                      value: OperatorA
                    containedInPlace:
                      type: Property
                      value:
                        type: Polygon
                        coordinates:
                          - - - 100
                              - 0
                            - - 101
                              - 0
                            - - 101
                              - 1
                            - - 100
                              - 1
                            - - 100
                              - 0
                    '@context':
                      - 'https://schema.lab.fiware.org/ld/context'
                      - 'https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld'



  /nsgi-v2:
    get:
      responses:
        200:
          description: "Invalid input"
          content:
            application/json:
              examples: 
                normalized:
                  summary: Normalized example
                  value: 
                    id: building-a85e3da145c1
                    type: Building
                    category:
                      value:
                       - office
                    floorsBelowGround:
                      value: 0
                    description:
                      value: Office block
                    floorsAboveGround:
                      value: 7
                    occupier:
                      type: Relationship
                      value:
                        - 9830f692-7677-11e6-838b-4f9fb3dc5a4f
                    mapUrl:
                      type: URL
                      value: 'http://www.example.com'
                    dateCreated:
                      type: DateTime
                      value: '2016-08-08T10:18:16Z'
                    source:
                      value: 'http://www.example.com'
                    location:
                      type: 'geo:json'
                      value:
                        type: Polygon
                        coordinates:
                         - - - 100
                             - 0
                           - - 101
                             - 0
                           - - 101
                             - 1
                           - - 100
                             - 1
                           - - 100
                             - 0
                        address:
                          type: PostalAddress
                          value:
                             addressLocality: London
                             postalCode: EC4N 8AF
                             streetAddress: 25 Walbrook
                        owner:
                          type: Relationship
                          value:
                             - cdfd9cb8-ae2b-47cb-a43a-b9767ffd5c84
                             - 1be9cd61-ef59-421f-a326-4b6c84411ad4
                        openingHours:
                          value:
                             - 'Mo-Fr 10:00-19:00'
                             - 'Sa 10:00-22:00'
                             - 'Su 10:00-21:00'
                        dataProvider:
                          value: OperatorA
                        dateModified:
                           type: DateTime
                           value: '2016-08-08T10:18:16Z'
                        containedInPlace:
                           value:
                             type: Polygon
                             coordinates:
                               - - - 100
                                   - 0
                                 - - 101
                                   - 0
                                 - - 101
                                   - 1
                                 - - 100
                                   - 1
                                 - - 100
                                   - 0
                         
                  
                  
                  
                keyvalues:
                  summary: Key-Values Pairs
                  value: 
                   id: building-a85e3da145c1
                   type: Building
                   dateCreated: '2016-08-08T10:18:16Z'
                   dateModified: '2016-08-08T10:18:16Z'
                   source: 'http://www.example.com'
                   dataProvider: OperatorA
                   category:
                     - office
                   containedInPlace:
                     type: Polygon
                     coordinates:
                       - - - 100
                           - 0
                         - - 101
                           - 0
                         - - 101
                           - 1
                         - - 100
                           - 1
                         - - 100
                           - 0
                   location:
                     type: Polygon
                     coordinates:
                       - - - 100
                           - 0
                         - - 101
                           - 0
                         - - 101
                           - 1
                         - - 100
                           - 1
                         - - 100
                           - 0
                   address:
                     addressLocality: London
                     postalCode: EC4N 8AF
                     streetAddress: 25 Walbrook
                   owner:
                     - cdfd9cb8-ae2b-47cb-a43a-b9767ffd5c84
                     - 1be9cd61-ef59-421f-a326-4b6c84411ad4
                   occupier:
                     - 9830f692-7677-11e6-838b-4f9fb3dc5a4f
                   floorsAboveGround: 7
                   floorsBelowGround: 0
                   description: Office block
                   mapUrl: 'http://www.example.com'
                   openingHours:
                     - 'Mo-Fr 10:00-19:00'
                     - 'Sa 10:00-22:00'
                     - 'Su 10:00-21:00'
                 


    
components:
  schemas:
    Categories:
      type: string
      x-uri-prefix: "https://uri.fiware.org/ns/data-models#"
      description: >
            URN holding the id of the attribute
      enum: &CATEGORIES
        - apartments
        - farm
        - hotel
        - house
        - detached
        - residential
        - dormitory
        - terrace
        - houseboat
        - bungalow
        - static_caravan
        - commercial
        - office
        - industrial
        - retail
        - warehouse
        - kiosk
        - bakehouse
        - cathedral
        - chapel
        - church
        - kindergarten
        - mosque
        - temple
        - synagogue
        - shrine
        - civic
        - hospital
        - school
        - stadium
        - train_station
        - transportation
        - university
        - grandstand
        - public
        - barn
        - bridge
        - bunker
        - cabin
        - carport
        - conservatory
        - construction
        - cowshed
        - digester
        - farm_auxiliary
        - garage
        - garages
        - garbage_shed
        - greenhouse
        - hangar
        - hut
        - pavilion
        - parking
        - riding_hall
        - roof
        - shed
        - stable
        - sty
        - transformer_tower
        - service
        - ruins
        - water_tower
        
        

      
    Building:
      required:
        - address
        - category
        
      description: >
        ## Description
  
        This entity contains a harmonised description of a Building. This entity is
        associated with the vertical segments of smart homes, smart cities, industry and
        related IoT applications.
        
        This data model has been partially developed in cooperation with mobile
        operators and the [GSMA](https://www.gsma.com/iot/iot-big-data/), compared to
        GSMA data model following changes are introduced:
        
        -   the reference to `BuildingType` is removed, since `BuildingType` compared to
            `category` attribute does not introduce significant information.
        
        -   `category` attribute is required.
        
        -   `openingHours` is introduced following schema.org data model to allow
            fine-grained on building opening times. GSMA supported this as free text in
            the `notes` attribute (removed as well).
        
        -   `refSubscriptionService` is not supported, since `SubscriptionService` model
            is not supported currently.
        
        ## Data Model
        
        For a full description of the following attributes refer to GSMA
        [IoT Big Data Harmonised Data Model](https://github.com/GSMADeveloper/NGSI-LD-Entities)
      
      
      type: "object"
      allOf:
        - $ref: "https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/Common"
        - $ref: "https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/Movable"
        
        
      properties:
      
        address:
          $ref: "https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/Address"
        
        category:
          x-attr-type: "EnumProperty"
          type: "string"
          enum: *CATEGORIES
          description: >
            The categories that this building belongs to
      
    
        containedInPlace :
          x-attr-type: "Relationship"
          x-model: "https://schema.org/URL"
          type: "string"
          format: "URL"
          description: >
            The URL this building resides within  
       
            
        dataProvider:
          x-attr-type: "Property"
          x-model: "https://schema.org/URL"
          type: "string"
          format: "URL"
          description: >
            Specifies the URL to information about the provider of this information
          

        description:
          $ref: 'https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/Description'
          
          
        floorsAboveGround:
          x-attr-type: "Property"
          x-model: "https://schema.org/Integer"
          type: "integer"
          format: "int32"
          description: >
            Number of floors above ground within the building


        floorsBelowGround:
          x-attr-type: "Property"
          x-model: "https://schema.org/Integer"
          type: "integer"
          format: "int32"
          description: >
            Number of floors below ground within the building

        occupier:
          x-attr-type: "Relationship"
          x-model: "https://schema.org/URL"
          type: "string"
          format: "URL"
          description: >
            Link to the occupiers of the building

        openingHours :
          x-attr-type: "Property"
          x-model: "https://schema.org/openingHours"
          type: array
          items:
            type: object
            properties:
              type: 
                type: string
              values: 
                type: array
                items:
                  type: string
                  
        owner :
          x-attr-type: "Relationship"
          x-model: "https://schema.org/URL"
          type: "string"
          format: "URL"
          description: >
            The owner of this building
          externalDocs:
            url: "https://schema.org/openingHours"

        refMap :
          x-attr-type: "Property"
          x-model: "https://schema.org/URL"
          type: "string"
          format: "URL"
          description: >
            The URL holding a map of the building
            
            
        source2 :
          x-attr-type: "Property"
          x-model: ["https://schema.org/Text", "https://schema.org/URL"]
          type: "string"
          description: >



            
        source:
          x-attr-type: "Property"
          x-model: ["https://schema.org/Text", "https://schema.org/URL"]
          type: "string"
          description: >
            A sequence of characters giving the source of the entity data.



          
