Building:
  required:
    - type
    - id
    - category
    - address
  allOf:
    - $ref: 'https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/Common'
  type: object
  description: Information on a given Building
  properties:
    address:
      $ref: 'https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/address'
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    category:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - apartments
          - farm
          - hotel
          - house
          - detached
          - residential
          - dormitory
          - terrace
          - houseboat
          - bungalow
          - static_caravan
          - commercial
          - office
          - industrial
          - retail
          - warehouse
          - kiosk
          - bakehouse
          - cathedral
          - chapel
          - church
          - kindergarten
          - mosque
          - temple
          - synagogue
          - shrine
          - civic
          - hospital
          - school
          - stadium
          - train_station
          - transportation
          - university
          - grandstand
          - public
          - barn
          - bridge
          - bunker
          - cabin
          - carport
          - conservatory
          - construction
          - cowshed
          - digester
          - farm_auxiliary
          - garage
          - garages
          - garbage_shed
          - greenhouse
          - hangar
          - hut
          - pavilion
          - parking
          - riding_hall
          - roof
          - shed
          - stable
          - sty
          - transformer_tower
          - service
          - ruins
          - water_tower
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/description
    floorsAboveGround:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Integer'
      type: integer
      description: ''
      format: int32
    floorsBelowGround:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Integer'
      type: integer
      description: ''
      format: int32
    location:
      $ref: 'https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/location'
    name:
      $ref: 'https://jason-fox.github.io/swagger-datamodel-test/common.yaml#/name'
    occupier:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        oneOf:
          - type: string
            format: uri
          - &ref_0
            anyOf:
              - type: string
                minLength: 1
                maxLength: 256
                pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              - type: string
                format: uri
    openingHours:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items: *ref_0
    refMap:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
