openapi: 3.0.0
info:
  description: ''
  version: 1.0.0
  title: Harness

tags: 
  - name: ngsi-ld
    description: >
      NGSI-LD Linked-data Format
  - name: ngsi-v2
    description: >
      NGSI-v2 Format
  

paths: 
  /ngsi-ld:
    get:
      tags:
        - ngsi-ld
      responses:
        '200':    # status code
          description: None
          content:
            application/json:
              schema: 
                type: object
 

components:
  schemas:
    # Use the Smart Data Models definition of a Building
    Building:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/building.yaml#/Building
    # Use the Smart Data Models definition of a Device
    Device:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/device.yaml#/Device
    # Use the GeoJSON definitions for various Geographical type
    Point:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/geojson-ld.yaml#/Point
    LineString:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/geojson-ld.yaml#/LineString
    Polygon:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/geojson-ld.yaml#/Polygon
    MultiPoint:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/geojson-ld.yaml#/MultiPoint
    MultiLineString:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/geojson-ld.yaml#/MultiLineString
    MultiPolygon:
      $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/geojson-ld.yaml#/MultiPolygon
    

    # Extend an existing model to create a new type with an attribute 
    TemperatureSensor:
      type: object
      required:
        -  temperature
      allOf:
        - $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/device.yaml#/Device

      description: >
        A device that consists of a sensor, has category `saref:Sensor` and is used for the purpose of sensing temperature`.
      
      properties:
        temperature:
          $ref: https://jason-fox.github.io/swagger-datamodel-test/swagger/models/saref-terms.yaml#/temperature
