openapi: 3.0.0
info:
  description: ''
  version: 1.0.0
  title: TemperatureSensor

tags: 
  - name: ngsi-ld
    description: >
      NGSI-LD Linked-data Format
  - name: ngsi-v2
    description: >
      NGSI-v2 Format
  

paths: 
  /ngsi-ld:
    get:
      tags:
        - ngsi-ld
      responses:
        '200':    # status code
          description: None
          content:
            application/json:
              schema: 
                type: object
 

components:
  schemas:
     TemperatureSensor:
      type: object
      required:
        -  temperature
      allOf:
        - $ref: ./models/device.yaml#/Device

      description: >
        A device that consists of a sensor, has category `saref:Sensor` and is used for the purpose of sensing temperature`.
      
      properties:
        temperature:
          $ref: ./models/saref-terms.yaml#/temperature